### ISSUE TITLE
Ngx-Gallery Image Preview Z-index

### ISSUE THREAD

**Issue by resuta566** [lukasz-galka/ngx-gallery#290]
How can I change the gallery Image preview Z-index?

Here is a screenshot.
 [Link](https://i.imgur.com/KzOFh7g.png) 

My navbar is overlapping with the preview

**Comment by resuta566** [comment]
Welp, I don't know why but my issue is fixed lol.

**Comment by WajeehAbiad** [comment]
how could you solve this problem???
My navbar still appears in front of the ngx-gallery-preview
