### ISSUE TITLE
Slide problem

### ISSUE THREAD

**Issue by junimohano** [lukasz-galka/ngx-gallery#30]
Slide should be only horizontal not vertical.
in terms of mobile, scroll is not working when I touched to scroll down on ngx-gallery.

**Comment by lukasz-galka** [comment]
Hi @junimohano I have fixed this in version 1.1.3. Please check and let me know.

**Comment by junimohano** [comment]
This is not fixed...
It doesn't scroll when I touch down on pic and drag to up or down on imageSwipe mode.

**Comment by lukasz-galka** [comment]
Could you check here https://lukasz-galka.github.io/ngx-gallery-demo/#swipe ?

**Comment by junimohano** [comment]
hm.... even I updated... why it is not working ??
your demo is okay... but why mine is not working ;;;

**Comment by junimohano** [comment]
on thumnails are okay.. only on just pictures

**Comment by lukasz-galka** [comment]
Do you still have this problem? Maybe could you update your test repository and I will check there?

**Comment by lukasz-galka** [comment]
I'm closing this ticket, if you still have problems let me know.

**Comment by PepeBel4** [comment]
Hello,
Old topic, but i still encounter this issue.
Testing on iPad. Vertical swipe on thumbnails is ok; but nothing happens when swiping vertical on the images. When using the gallery almost fullscreen on iPad, this is really blocking issue. 

Very very nice component, with plenty of configuration options!

**Comment by harm-less** [comment]
I can confirm this issue as I'm experiencing the same thing
